# Generated by Django 2.2.10 on 2020-02-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('last_update', models.DateField()),
                ('read_me', models.TextField()),
                ('url', models.URLField()),
                ('github_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
